### ISSUE TITLE
Versioning on Pi-Star F1RMB

### ISSUE THREAD

**Issue by bderry71** [f1rmb/Pi-Star_DV_Dash#1]
It seems you have a bug in your versioning of your custom release of Pi-Star. Every time I run the upgrade from the Web interface the version number increments even though it didn't do anything. 

Correct handling of that would be to only increment when there was an update applied.

**Comment by f1rmb** [comment]
Hi,

  That's the case, just like on a pristine PiStar. If the version number keeps increasing, that only means that you're not up to date (FIY, latest V4 is 4.1.8, and dashboard version is from Jan 24th).
