### ISSUE TITLE
Upgrade not work 

### ISSUE THREAD

**Issue by DL7PJ** [f1rmb/Pi-Star_DV_Dash#2]
![image](https://user-images.githubusercontent.com/46009291/107997545-4a50ca00-6fe3-11eb-907f-f695e39b5b03.png)

**Comment by f1rmb** [comment]
Can you give me the result of the following command:

`git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git remote -v | grep origin`

or 

`./f1rmb-pistar -s
`

**Comment by DL7PJ** [comment]
Hello and tnx fer Answer 
![image](https://user-images.githubusercontent.com/46009291/108092893-73259d80-707d-11eb-854a-b34203f5dc7e.png)

**Comment by f1rmb** [comment]
Ah, I see. In fact, you're not using my fork, but the one made from "msraya" (https://github.com/msraya).
You should ask him to fix his fork made out of my fork ;-)

**Comment by DL7PJ** [comment]
Néanmoins, merci beaucoup Daniel pour vos efforts
gd DX 73 de Peter

**Comment by f1rmb** [comment]
Merci Peter.
Pour votre problème, je ne peux absolument rien faire, Manuel doit corriger son fork pour ça.

73.
---
Daniel
