### ISSUE TITLE
XLX Module missing on main page.

### ISSUE THREAD

**Issue by VA3DBJ** [f1rmb/Pi-Star_DV_Dash#3]
The module for a XLX link is not showing on the main screen, as it does on the regular pi-star version.

**Comment by f1rmb** [comment]
Hi,

  Do you mean here ?:
![image](https://user-images.githubusercontent.com/10473896/117704574-46d87380-b1cb-11eb-8b7d-14819a69024b.png)

**Comment by VA3DBJ** [comment]
Yes.  I have a nasty habit of changing modules on the weekends and 
seeing which one I was on, would be helpful.  I just changed to your 
version f1rmb this morning and just noticed it, when I brought up the 
Western New York 891 link.

   :)

------ Original Message ------

**Comment by f1rmb** [comment]
that's weird, as the above image is from one of my hotspots...

**Comment by f1rmb** [comment]
Have you tried to apply the configuration (within the Configuration page) ?

**Comment by f1rmb** [comment]
BTW, that is your dashboard version ?

**Comment by VA3DBJ** [comment]
Instead if just showing XLX313. should it not show XLX313 C, if you are 
on module C?  That is what the default pi-star 4.1.4 shows.

I am not trying to be a pain.  I thought it might have been a bug, as i 
got so used to the format that 4.1.4 and earlier had.  That way you can 
see that you are on module/room C on the XLX link.

------ Original Message ------

**Comment by VA3DBJ** [comment]
4.1.11RBM  20210505-f1rmb

------ Original Message ------

**Comment by f1rmb** [comment]
Oh, okay, I see what you mean.
... checking ...

**Comment by VA3DBJ** [comment]
![image](https://user-images.githubusercontent.com/40520974/117723930-0b30b000-b1b1-11eb-8508-38eb21e933c3.png)

Hope my pic shows above.

**Comment by f1rmb** [comment]
Yes. I think there is a bug in the code, I'm fixing it.

**Comment by VA3DBJ** [comment]
Thank you.  :)  I did try this version a while back, but gave it another try this morning, and I like a lot of what has been implemented.  :)  Thanks for the hard work.

**Comment by f1rmb** [comment]
Thanks, happy you like it ;-)

**Comment by f1rmb** [comment]
Okay, it's fixed now.
Just update your hotspot.

Thanks for the report ;-)

**Comment by VA3DBJ** [comment]
Yes sir it is.  :)

![image](https://user-images.githubusercontent.com/40520974/117726889-3ddca780-b1b5-11eb-81ca-dcd0cc67de90.png)

Perfect.  Thanks again.
